version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf # Mount postgresql.conf
    command: ["postgres", "-c", "log_statement=all"]

  redis:
    image: redis:latest

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/app_db
      - |
        ROCKET_DATABASES={
          postgres={url=postgres://postgres:postgres@postgres/app_db},
          redis={url=redis://redis:6379}
        }
      - SMTP_HOST=smtp.gmail.com
      - SMTP_USERNAME=weldonkipchirchir23@gmail.com
      - SMTP_PASSWORD=plltuyjrxqgkmlwx
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  default:
    external: true
    name: crate_registry_default
