version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all", "-c", "listen_addresses='*'"]

  redis:
    image: redis:latest

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/app_db
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  default:
    external:
      name: crate_registry_default
